"""change account attributs parameter

Revision ID: 3082e097c908
Revises: f2712699b31d
Create Date: 2024-04-29 14:31:42.659918

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3082e097c908'
down_revision = 'f2712699b31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('deleted',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              existing_server_default=sa.text('false'))
        batch_op.alter_column('locked',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              existing_server_default=sa.text('false'))
        batch_op.alter_column('to_keep',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              existing_server_default=sa.text('false'))
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              autoincrement=True,
                              nullable=False)
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_id',
                              existing_type=sa.INTEGER(),
                              autoincrement=True,
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('to_keep',
                              existing_type=sa.BOOLEAN(),
                              nullable=True,
                              existing_server_default=sa.text('false'))
        batch_op.alter_column('locked',
                              existing_type=sa.BOOLEAN(),
                              nullable=True,
                              existing_server_default=sa.text('false'))
        batch_op.alter_column('deleted',
                              existing_type=sa.BOOLEAN(),
                              nullable=True,
                              existing_server_default=sa.text('false'))
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              autoincrement=False,
                              nullable=True)
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_id',
                              existing_type=sa.INTEGER(),
                              autoincrement=False,
                              nullable=True)

    # ### end Alembic commands ###
