"""ajout colonne pré-supression

Revision ID: 5edef9a1aab0
Revises: 2500e2917b06
Create Date: 2024-05-16 14:55:04.336449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edef9a1aab0'
down_revision = '2500e2917b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_deleted', sa.Boolean(), nullable=True, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('pre_deleted')

    # ### end Alembic commands ###
