"""add pwd column to user

Revision ID: 61987409fd78
Revises: bfd5eeb09e82
Create Date: 2024-05-23 13:40:18.164851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61987409fd78'
down_revision = 'bfd5eeb09e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
