"""remove uid

Revision ID: 8cb939417a77
Revises: 6a87b5f158d7
Create Date: 2024-06-11 12:47:33.324764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb939417a77'
down_revision = '6a87b5f158d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('ix_account_uid')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_account_uid', ['uid'], unique=True)

    # ### end Alembic commands ###
