"""changement nullable pre_deleted

Revision ID: c8ba0e30713f
Revises: 5edef9a1aab0
Create Date: 2024-05-16 15:01:38.926141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ba0e30713f'
down_revision = '5edef9a1aab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('pre_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('pre_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
